{"uuid": "1ff09110-dd18-488a-a927-15442d0aa74d", "children": ["d263b5fd-e2c4-44f4-92ba-da5652d44547", "0f826863-e43d-43f8-a6f2-a70a5b44c68e", "61389121-65ba-4ba0-ab59-b5fe781561df", "677b04e0-a35b-419b-927a-7fbd73212869", "e3d761e3-1bf8-4b8f-bb39-9fce11f74de2", "a41d75b9-f8ca-4d92-b2c8-0b3e8c3a2fb5", "b2e9c291-d912-4469-8f53-0adeee825b7a", "23132169-e81b-49e9-ac1c-913c1691a2ac", "ab5b13cd-be72-4006-8f23-606cd136dc03", "5fe54dc5-64e1-43b6-b940-cdc8e9236d66", "c14baf78-36e6-4f8d-b151-316a8020e7f6", "e23b119a-ed97-4c24-853a-1622e036920f", "3d174c73-80a1-4214-8dce-b3105ebb6c97", "0e3b4cda-a187-41fe-98d7-68caa58c9ad8"], "befores": [{"name": "__init__", "status": "failed", "statusDetails": {"message": "AssertionError: None\nassert 'http://10.250.112.166:9000/#/dashboard' in 'http://10.250.112.166:9000/#/'\n", "trace": "  File \"D:\\app\\Python10\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\app\\Python10\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\app\\Python10\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\售后自动化\\UIPOMTest\\project\\DRP\\test_case\\conftest.py\", line 22, in __init__\n    user.assert_url(\"{}/dashboard\".format(ini.url))\n  File \"D:\\app\\Python10\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"D:\\售后自动化\\UIPOMTest\\public\\base\\assert_ui.py\", line 189, in assert_url\n    assert word in att, logging.warning(\"断言失败：URL为预期不一致 | URL: {}\".format(att))\n"}, "steps": [{"name": "值为True值断言", "status": "failed", "statusDetails": {"message": "AssertionError: None\nassert 'http://10.250.112.166:9000/#/dashboard' in 'http://10.250.112.166:9000/#/'\n", "trace": "  File \"D:\\app\\Python10\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"D:\\售后自动化\\UIPOMTest\\public\\base\\assert_ui.py\", line 189, in assert_url\n    assert word in att, logging.warning(\"断言失败：URL为预期不一致 | URL: {}\".format(att))\n"}, "parameters": [{"name": "word", "value": "'http://10.250.112.166:9000/#/dashboard'"}], "start": 1658731479820, "stop": 1658731481339}], "start": 1658731459035, "stop": 1658731481342}], "start": 1658731459035, "stop": 1658731492071}